# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            extractions
tagline:          'extractions'
description:      'What and where the data is.'

author:
  name:           'Aurelie Albert'


paginate:         2
google_analytics: 'UA-91425204-3'
bing_seo:		  'ECA8D4503D79297E7BB223666F18CAF8'
emailme:          mailto:aurelie.albert@ocean-next.fr

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://aureliealbert.github.io/new-catalog-extractions
tags:

github_username:  AurelieAlbert
